### ISSUE TITLE
Complete Ui design

### ISSUE THREAD

**Issue by vikraman-boominathan** [just-vicky/Eco-service#1]
![Screenshot from 2024-03-15 11-34-48](https://github.com/just-vicky/Eco-service/assets/93125965/82d149f8-4fbf-4dc7-8151-6e2f09c56c2d)
Implement the above ui

**Comment by rahul190201** [comment]
@just-vicky Reduce the category input fields to half width, in the remaining half space, add input fields for entering amount in kg.

So it should look something like this:
Category 1
| No. of bags        |      Weigth in kg     |   pencil icon

**Comment by vikraman-boominathan** [comment]
![image](https://github.com/just-vicky/Eco-service/assets/93125965/361604b7-0cf0-4c85-9421-f5cff4ad58ab)

@rahul190201 I have already made it in the above model.
